const cuisines = {
  title: "Popular cuisines near me",
  values: [
    "Arabian food near me",
    "Bakery food near me",
    "Beverages food near me",
    "Biryani food near me",
    "Chinese food near me",
    "Continental food near me",
    "Burger food near me",
    "Desserts food near me",
    "Ice Cream food near me",
    "Italian food near me",
    "Juices food near me",
    "Kerala food near me",
    "Lebanese food near me",
    "North Indian food near me",
    "Pizza food near me",
    "Seafood food near me",
    "Shake food near me",
    "Shawarma food near me",
    "South Indian food near me",
    "Street food near me me",
  ],
};

const restaurants = {
  title: "Popular restaurant types near me",
  values: [
    "Bakeries near me",
    "Bars near me",
    "Beverage Shops near me",
    "Cafés near me",
    "Casual Dining near me",
    "Dessert Parlors near me",
    "Fine Dining near me",
    "Food Courts near me",
    "Kiosks near me",
    "Quick Bites near me",
    "Sweet Shops near me",
  ],
};

const cities = {
  title: "Cities We Deliver To",
  values: [
    "Delhi NCR",
    "Kolkata",
    "Mumbai",
    "Bengaluru",
    "Pune",
    "Hyderabad",
    "Chennai",
    "Lucknow",
    "Kochi",
    "Jaipur",
    "Ahmedabad",
    "Chandigarh",
    "Goa",
    "Indore",
    "Gangtok",
    "Nashik",
    "Ooty",
    "Shimla",
    "Ludhiana",
    "Guwahati",
    "Amritsar",
    "Kanpur",
    "Allahabad",
    "Aurangabad",
    "Bhopal",
    "Ranchi",
    "Visakhapatnam",
    "Bhubaneswar",
    "Coimbatore",
    "Mangalore",
    "Vadodara",
    "Nagpur",
    "Agra",
    "Dehradun",
    "Mysore",
    "Puducherry",
    "Surat",
    "Varanasi",
    "Patna",
    "Udaipur",
    "Khajuraho",
    "Neemrana",
    "Cuttack",
    "Trivandrum",
    "Haridwar",
    "Leh",
    "Pushkar",
    "Rajkot",
    "Madurai",
    "Kozhikode",
    "Alappuzha",
    "Thrissur",
    "Manipal",
    "Vijayawada",
    "Jodhpur",
    "Kota",
    "Ajmer",
    "Mussoorie",
    "Rishikesh",
    "Jalandhar",
    "Jammu",
    "Manali",
    "Dharamshala",
    "Raipur",
  ],
};

module.exports = { cuisines, restaurants, cities };
